### ISSUE TITLE
"Sample Starter Code" causes error when trying to fetch departures

### ISSUE THREAD

**Issue by teelittle** [FahrplanDatenGarten/pyhafas#15]
### Steps to reproduce
Put the "[Sample Starter Code](https://pyhafas.readthedocs.io/en/stable/usage/get_started.html)" in a `.py` file and let it execute by the python interpreter. 

### Unexpected behaviour
Script returns location data, followed by an error message instead of departures data: 
`TypeError: departures() got an unexptected keyword argument 'max_journeys'`

### Cause of error 
The correct parameter to use with `HafasClient.departures` is `max_trips` (as documented [here](https://pyhafas.readthedocs.io/en/stable/usage/client.html)). 

### how to fix the unexpected behaviour 
Replace `max_journeys` parameter name with `max_trips`

**Comment by Peer202** [comment]
In Addition to that, the code makes a call for datetime.datetime..now() which is in the datetime module, which is not imported.

`import datetime does the job

**Comment by 1Maxnet1** [comment]
@leona-ya as you created a release yesterday, this issue is completely resolved now and can be closed imho
