### ISSUE TITLE
Get actual train number

### ISSUE THREAD

**Issue by 25334** [FahrplanDatenGarten/pyhafas#17]
Hey there,

is there a way to query the actual train number? As an example, I can get the number RE 59123, but not RE 16 (as it is probably displayed on the train itself)...

![grafik](https://user-images.githubusercontent.com/59446955/179350526-18f12f9c-0bda-4c1c-b561-20d6cc270ad7.png)

![grafik](https://user-images.githubusercontent.com/59446955/179350676-2240e891-2ea6-40bd-958e-3f8e2be57fd5.png)

Thanks and keep up the great work!

**Comment by philipp-leibner** [comment]
How did you solve it?
