### ISSUE TITLE
Add KVB profile (Kölner Verkehrsbetriebe)

### ISSUE THREAD

**Issue by akloeckner** [FahrplanDatenGarten/pyhafas#21]
I read in #12 that we should open an issue, if we would like to have a specific profile. So here's my issue for KVB. The metadata is in [transport-apis](https://github.com/public-transport/transport-apis/blob/v1/data/de/kvb-hafas-mgate.json). Maybe it's a matter of a few minutes for a maintainer to add this. I would for sure need a few days...

Why would I like to have it? While the planned journeys are also in the DB system, the realtime data is much more accurate in the local transport provider's system. And I want to use the data for displaying "next departures" of our local tramway station.

**Comment by 1Maxnet1** [comment]
I will give it a try this week :)

**Comment by akloeckner** [comment]
Nice, thanks a lot! Let me know, if I can somehow help with my limited insight in the interface.

**Comment by 1Maxnet1** [comment]
I started my work here: https://github.com/1Maxnet1/pyhafas/tree/kvb-profile You can have a look at the Profile, and let me know, if any namings do not fit the local naming scheme :) I did not yet try it out and will create some tests for that before I create a PR

**Comment by akloeckner** [comment]
Are you referring to the product names?

I have taken a screenshot from our KVB trip planner app:

![Screenshot_20230517_134827](https://github.com/FahrplanDatenGarten/pyhafas/assets/7125061/b4c59811-e632-4c71-b0f1-038d39084967)

I'm not sure where those names are used. I have only found some comments here: 

https://github.com/1Maxnet1/pyhafas/blob/d44133e9258d7b473bb56813e3c2199a6729f04b/pyhafas/profile/kvb/__init__.py#L32

I would suggest to use
* Fernverkehr
* Regionalverkehr
* S-Bahn
* Stadtbahn, U-Bahn
* Bus

Why?

The `tram` is in fact both above ground (Stadtbahn/Straßenbahn) and underground (U-Bahn). The `long-distance` and `regional` types are not limited to the products listed in the comments, I believe. For example, the TGV and Thalys stop in Cologne, too. And I have no idea what a `taxibus` is. :-)

**Comment by 1Maxnet1** [comment]
Thanks for the input, I just double checked the publicly available configuration file (https://github.com/public-transport/transport-apis/blob/v1/data/de/kvb-hafas-mgate.json) and adjusted my naming (For the VSN which is already supported by this repository, the names match their respective configuration as well, so it is consistent). It almost fits your proposed names, so I would go with this for now. If you later have any issues in your application, we can figure out how to handle the names.

**Comment by akloeckner** [comment]
Looks good! Thanks!

**Comment by 1Maxnet1** [comment]
I updated my branch again. Except for Journeys the tests seem to work fine. Will take a lot at that soon.

**Comment by 1Maxnet1** [comment]
I just created a PR with my initial work: #28 Please have a look and test it out, whether you find any issues.

**Comment by leona-ya** [comment]
Solved in #28. I also tested it works.

**Comment by akloeckner** [comment]
Thanks for adding the KVB provider! Would you mind to create a new relase, so I can use the new profile in https://github.com/akloeckner/hacs-hafas? If you'd like to finish #24 first, I'm also fine with that. :-)

**Comment by leona-ya** [comment]
Will release now.

**Comment by akloeckner** [comment]
Perfect, thanks!
